### ISSUE TITLE
`bitmap "icon.ico" not defined` on Linux

### ISSUE THREAD

**Issue by fcard** [Lokno/SwitchSendToPC#2]
I managed to adapt the install command for Linux:
```sh
sudo pyinstaller -F --add-data="icon.ico:." --windowed --icon icon.ico ./switch_send_to_pc.py
```
Unfortunately pyinstaller gives a warning:
```
337 WARNING: Ignoring icon; supported only on Windows and macOS!
```
And when I try to run the command I get this error:
```sh
nmcli tool, version 1.36.6
Traceback (most recent call last):
  File "/home/phi/Source/SwitchSendToPC/switch_send_to_pc.py", line 394, in <module>
    live_feed = ConnectSwitchWifi(root)
  File "/home/phi/Source/SwitchSendToPC/switch_send_to_pc.py", line 71, in __init__
    root.iconbitmap(get_resource_path("icon.ico"))
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "icon.ico" not defined
```

**Comment by Lokno** [comment]
I unfortunately do not have a Linux machine to test pyinstaller compilation at this time. Therefore, these instructions assumed Windows compilation. This has been clarified in the README. I have also added a check for this exception so the program will not quietly move on without loading the icon. See commit 6db02fc2803833d39ac55b9e9451682682811e0f

Keep in mind that compilation using pyinstaller is optional. This is how I produce the binary on the release page. You may run the program directly with python:

`python switch_send_to_pc.py`

**Comment by fcard** [comment]
Aah, so the pyinstaller thing is just for the windows binary then. I thought it produced the python script as an output somehow (I forgot to check if it wasn't there already, hehe)

The error at the end that I get is from running it as `sudo python switch_send_to_pc.py`. I need sudo or I get a "The user doesn't have permission for wifi" error or somesuch. Well, since it isn't pyinstaller and you don't have a linux machine I will take a look around the code and see if I can figure it out, I should have some free time today. I will report back.

**Comment by Lokno** [comment]
Thank you. I would love to support Linux so I'm grateful for your help on this. I have written code that theoretically would work and went as far as testing the actual commands on a raspberry pi, but outside of that I have not done any additional testing.
