### ISSUE TITLE
Old versions of Pillow don't work

### ISSUE THREAD

**Issue by fcard** [Lokno/SwitchSendToPC#3]
I forgot to file this one the other day, but, there's a minimum required version of Pillow needed, so I think just checking for it isn't enough. I couldn't figure out the exact version, but, I had `9.0.1` and it gave me this error:
```
Traceback (most recent call last):
  File "/home/phi/Source/SwitchSendToPC/switch_send_to_pc.py", line 38, in <module>
    from PIL import ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```
I suppose just doing a try-catch on this line (`from PIL import ImageTk`) and asking the user to `pip install Pillow --upgrade` would work, since that's what solved it for me.

**Comment by Lokno** [comment]
I'm not able to repro this error on my end. I went as far back as pillow 8.4.0 on a raspberry pi and I was still able to import ImageTk. I tried digging through pillow release notes, but I'm not turning up when the ImageTk module was introduced. Is there any additional information you could provide me about your development environment? Thanks.

**Comment by Lokno** [comment]
I have partially addressed this issue by adding more detail to running requirements in the README. Commit 453b0d1dad01aca4cb1ef372e5792310337c716a

**Comment by fcard** [comment]
Hmm, I went back thru my terminal's log from when I was trying to run the program and the only related thing I saw was this suspicious message when I updated Pillow:
```
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.0.1
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
Successfully installed Pillow-9.4.0
```
So maybe the old version wasn't properly installed... I installed `Pillow==9.0.1` and it worked, so clearly the version wasn't the issue.

I can repro the issue by uninstalling Pillow all together, which will make python fall back to the broken library, which I am not sure how it became broken in the first place. Perhaps I didn't have TK installed when I installed Pillow, and because it wasn't in the pip path anymore it wasn't updated? Well, regardless, a much less pressing/common issue than it being an old version.

**Comment by Lokno** [comment]
Thank you for following up on this. I will close this issue for now since it seems like the solution is straightforward and not an issue with the application. But I'll continue to the requirements in the README and error messages in future updates.
